# Tips

## Keys to success

- Treat your data as read-only
- Comment code early and often
- Keep code chunks small
- Label chunks for diagnosing issues
- Nest all files under one directory (if possible)

## General information

- Escape characters with a backslash \\ (this also applies to any chunk output containing strings)
- Call R objects and functions in markdown/YAML by \~sandwiching\~ with backticks \`\`
- Automatic bracket/quote/asterisk wrapping
- Dollar signs for $\LaTeX$ math mode (but also be careful with pandoc)
- Line spacing matters in markdown

## Reference documents

- [R Markdown Guide](https://bookdown.org/yihui/rmarkdown/)
- [R Markdown Cheat Sheet](https://rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf)
- [R Markdown Reference Guide](https://rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf)
- [Keyboard shortcuts](https://support.rstudio.com/hc/en-us/articles/200711853-Keyboard-Shortcuts)
- [`knitr` documentation](https://yihui.org/knitr/)

## Other packages/tools

- [Sublime Text](https://www.sublimetext.com/3) text editor
- [`scholar` package](https://github.com/jkeirstead/scholar) for automatically downloading citations from Google Scholar
- `devtools` package for installing packages/plug-ins from GitHub (e.g., `papaja`)
- [wordcountaddin plug-in](https://github.com/benmarwick/wordcountaddin) for checking word count and readability

## Updating software/packages

- [Update your TeX distribution](https://tex.stackexchange.com/questions/55437/how-do-i-update-my-tex-distribution) from the command line
- Update all packages (including `rmarkdown`) in library with `update.packages(path)` 
- Update individual packages by reinstalling with `install.packages(package)`
- Update R in the console with `updateR` package
- Redownload RStudio to update