---
title: "R Markdown for Psychology Graduate Students"
author: "Holly Zaharchuk"
date: "`r Sys.Date()`"
output: 
  revealjs::revealjs_presentation:
    theme: white
    center: true
    transition: slide
    self_contained: true
    reveal_options:
      slideNumber: true
      progress: true
---

# The problem

- R Markdown is a highly useful platform for combining data processing/analysis and presentation
- There's a steep learning curve for really getting comfortable with R Markdown beyond the basics
- Graduate students are short on time

# The approach

How can I make R Markdown approachable and efficient to use for graduate students like me?

# The solution

- Started with tutorial for Cognitive Area Brownbag meeting
- Learned how to use `bookdown` to create a quick guide
- Created an [online guide hosted on GitHub](https://hollzzar.github.io/rmarkdown-guide/)

## [Welcome](https://hollzzar.github.io/rmarkdown-guide/index.html)

What is R Markdown and why should you use it?

## [Parts of a document](https://hollzzar.github.io/rmarkdown-guide/intro.html)

1. YAML header
2. Markdown
3. Code chunks

## [Outputs](https://hollzzar.github.io/rmarkdown-guide/output.html)

R Markdown can transform plain text and code into several different document formats. There are also multiple ways to **Knit** or `render` the output.

## [Templates](https://hollzzar.github.io/rmarkdown-guide/template.html)

1. Built-in templates
2. Templates from R packages
3. User-defined templates

## [Content](https://hollzzar.github.io/rmarkdown-guide/content.html)

The content of an R Markdown document includes the markdown text itself, as well as output from code chunks. Code chunks can output data, graphs, tables, and images. You can also reference variables from code chunks in markdown text.

## [Formatting](https://hollzzar.github.io/rmarkdown-guide/format.html)

There are many ways to customize the formatting of an R Markdown document. In the YAML header, you can specify different parameter options or reference external documents. You can also edit templates directly in certain cases. For local formatting, you can include inline code in the markdown sections.

## [Organization](https://hollzzar.github.io/rmarkdown-guide/organization.html)

Keeping documents and scripts organized is critical for reducing headaches (literal and figurative) when working on large R Markdown projects. This chapter covers `child` R Markdown documents and importing R scripts to keep your content organized.

## [Troubleshooting](https://hollzzar.github.io/rmarkdown-guide/trouble.html)

We've all been there. How can you avoid or handle warnings, errors, and other issues in R Markdown?

## Supplementary materials

- Beginner R
- Intermediate R
- `ggplot` tips and tricks
- Practice materials

# The future

- Dedicating a section to using GitHub
- How to make a website with R Markdown
- Build out practice materials

# The impact

This guide contributes to the enhancement of transparent, open, and reproducible scientific practices in the psychological sciences by equipping graduate students with the tools and knowledge to building effective research pipelines. R Markdown promotes clean and usable code that's easily shared and reproduced.